mkdir -p ./public/dash
mkdir -p ./public/book
mkdir -p ./public/admin/event
mkdir -p ./public/admin/tickets
mkdir -p ./public/admin/transactions
mkdir -p ./public/admin/users
mkdir -p ./public/css
mkdir -p ./public/js
mkdir -p ./public/lib/css
mkdir -p ./public/lib/js
mkdir -p ./public/lib/components
