insert into user (name, email, registration_time) values("Anita Magee","am2146@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Charlie Mercer","cm736@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Charlie Shotton","cshotton@gmail.com", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Christopher Little","cl554@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Daisy Savage","drs61@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("David Melleney","drjm4@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Eleanor Leydon","esrl2@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Eleanor Warr","ew435@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Ellie Cox","emc75@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Emma Meads","eym23@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Eve Edwards","eve_edwards@hotmail.co.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Ezra Neil","ezrajneil@gmail.com", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Felix Biggs","felixbig@gmail.com", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Finnbheara O'Dowd","fo222@emma.cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Frankie Tamblyn","fct24@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Garima Singhal","gs482@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Grace O'Neill","graceone66@btinternet.com", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Harriet Hall","hlh29@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Imogen Cara Flower","if249@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("James Hamilton","jekh3@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Jess Lister","jl833@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Jonathan Murphy","president@girtonball.co.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Katherine Macfarland","km587@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Keble Secretary","secretary@kebleball.com", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Kevin Dai","pd337@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Laura Brown","lb601@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Linda Thomson","ljt24@emma.cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Lydia Doster","lrd25@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Matt Sewell","mjs2134@yahoo.co.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Maxim Jones","mj432@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Millie Ngaage","milliengaage@msn.com", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Molly Llewellyn-Smith","mabl2@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Newnham","aol24@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Omar Mohamed","om298@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Roberta Huldisch","rnh24@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Stevie Hertz","sac93@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Thomas Le Feuvre","tl368@cam.ac.uk", UNIX_TIMESTAMP());
insert into user (name, email, registration_time) values("Tom Corder","tac21@cam.ac.uk", UNIX_TIMESTAMP());